#! /bin/sh
# Xreset - run as root after session exits

# Reassign ownership of the console to root, this should disallow
# assignment of console output to any random users's xterm. See Xstartup.
#
#chown root /dev/console
#chmod 622 /dev/console

# XDM configurations typically have sessreg here. KDM has it built-in.

# Use common Xreset framework if it exist
if [ -x /etc/X11/Xreset ] ; then
   /etc/X11/Xreset
fi