#! /bin/sh
# Xsetup - run as root before the login dialog appears

#xconsole -geometry 480x130-0-0 -notify -verbose -fn fixed -exitOnFail -file /dev/xconsole &

/sbin/initctl -q emit login-session-start DISPLAY_MANAGER=kdm
